### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/infografia-Lissete7-1#1]
![Infografía](https://user-images.githubusercontent.com/79929632/153807954-ffaed5ac-9606-4c0b-bff6-439d84cc4248.png)

**Comment by DuilioAquino10** [comment]
Calificación: 20.

**Comment by josealfredo79** [comment]
falta lo del estandar

**Comment by josealfredo79** [comment]
Bien hecho y revisado
